// Screen subset of https://www.w3.org/TR/cssom-view-1/
interface Screen {
  readonly attribute long width;
  readonly attribute long height;
  readonly attribute long availWidth;
  readonly attribute long availHeight;
  readonly attribute unsigned long colorDepth;
  readonly attribute unsigned long pixelDepth;
};

// Geometry returned by Element.getBoundingClientRect().
interface DOMRect {
  attribute double x;
  attribute double y;
  attribute double width;
  attribute double height;
  readonly attribute double top;
  readonly attribute double right;
  readonly attribute double bottom;
  readonly attribute double left;
};
