#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
NS_PREFIX="$SCRIPT_DIR/.deps/netsurf-workspace/inst-powerpc-eabi"
. "$SCRIPT_DIR/env.sh"

export PKG_CONFIG_DIR=
export PKG_CONFIG_PATH=
export PKG_CONFIG_SYSROOT_DIR=
export PKG_CONFIG_LIBDIR="$SCRIPT_DIR/.deps/optional/prefix/lib/pkgconfig:$NS_PREFIX/lib/pkgconfig:$SCRIPT_DIR/.deps/network/lib/pkgconfig:$DEVKITPRO/portlibs/wii/lib/pkgconfig:$DEVKITPRO/portlibs/ppc/lib/pkgconfig"

exec pkg-config --static "$@"
